#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]
	# -------------------------------
	# Commits to test upgrade from 6c44cf52521b423739b1399102fcc9ead5be6eab
	# 1.117.0~ynh2 with separeted microservices container/process
	# -------------------------------
	#	test_upgrade_from.6c44cf5.name = "1.117.0~ynh2"
	#	test_upgrade_from.6c44cf5.args.domain = "sub.domain.tld"
	#	test_upgrade_from.6c44cf5.args.init_main_permission = "visitors"
